name = "EpidemicsModel"
uuid = "b2226372-6578-448e-8bd5-d1bc018d08f8"
authors = ["Natan Dominko Kobilica"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
